import type { CountryAiSettings } from '../types';

export const COUNTRY_AI_CONFIGS: CountryAiSettings[] = [
  {
    countryCode: 'gn',
    language: 'fr',
    locale: 'fr-GN',
    countryName: 'Guinée',
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
      'IA',
      'Croissance',
      'Ventes',
      'E-commerce',
    ],
    topics: [
      'création entreprise Guinée',
      'gestion PME Conakry',
      'fiscalité DGI Guinée',
      'TVA 18% Guinée',
      'SYSCOHADA OHADA',
      'Orange Money commerce',
      'caisse POS Guinée',
      'marketing digital PME',
      'publicité Facebook Instagram Guinée',
      'WhatsApp Business commerce Conakry',
      'vendre en ligne Guinée',
      'e-commerce PME Afrique',
      'intelligence artificielle entreprises',
      'IA pour PME africaines',
      'développer son entreprise Guinée',
      'expansion PME Conakry',
      'productivité commerçants',
      'digitalisation boutique Conakry',
    ],
    sources: [
      { name: 'DGI Guinée', url: 'https://www.dgi.gov.gn', type: 'government', category: 'Fiscalité' },
      { name: 'Présidence de la République', url: 'https://presidence.gov.gn', type: 'government', category: 'Affaires' },
      { name: 'BCRG — Banque Centrale', url: 'https://www.bcrg-guinee.org', type: 'institution', category: 'Affaires' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution', category: 'Fiscalité' },
      { name: 'Orange Guinée Business', url: 'https://www.orangeguinee.com', type: 'business', category: 'Technologie' },
      { name: 'ARPT Guinée', url: 'https://www.arpt.gov.gn', type: 'government', category: 'Technologie' },
      { name: 'Google Ateliers Numériques', url: 'https://learndigital.withgoogle.com/ateliersnumeriques', type: 'education', category: 'Marketing' },
      { name: 'Meta Business', url: 'https://www.facebook.com/business', type: 'business', category: 'Marketing' },
      { name: 'CCI Guinée', url: 'https://www.cciguinee.org', type: 'business', category: 'Entrepreneuriat' },
    ],
  },
  {
    countryCode: 'sn',
    language: 'fr',
    locale: 'fr-SN',
    countryName: 'Sénégal',
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
      'IA',
      'Croissance',
      'Ventes',
      'E-commerce',
    ],
    topics: [
      'création entreprise Sénégal',
      'DGI Sénégal déclaration fiscale',
      'gestion PME Dakar',
      'SYSCOHADA Sénégal',
      'Wave Orange Money commerce Sénégal',
      'logiciel gestion restaurant Dakar',
      'TVA Sénégal entreprises',
      'marketing digital PME Sénégal',
      'publicité Facebook Instagram Dakar',
      'WhatsApp Business vente Sénégal',
      'vendre en ligne Sénégal',
      'e-commerce PME Dakar',
      'intelligence artificielle PME Sénégal',
      'développer son entreprise Dakar',
      'expansion PME Sénégal',
      'caisse POS boutique Dakar',
      'NINEA entreprise Sénégal',
      'digitalisation commerce Sandaga',
    ],
    sources: [
      { name: 'Ministère des Finances', url: 'https://www.finances.gouv.sn', type: 'government', category: 'Fiscalité' },
      { name: 'Ministère de l\'Économie', url: 'https://www.economie.gouv.sn', type: 'government', category: 'Affaires' },
      { name: 'Secrétariat d\'État à la Simplification', url: 'https://www.sec.gouv.sn', type: 'institution', category: 'Entrepreneuriat' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution', category: 'Fiscalité' },
      { name: 'CCIS', url: 'https://www.ccis.sn', type: 'business', category: 'Entrepreneuriat' },
      { name: 'ADEPME', url: 'https://www.adepme.sn', type: 'institution', category: 'Croissance' },
      { name: 'Orange Sénégal Business', url: 'https://www.orange.sn', type: 'business', category: 'Technologie' },
      { name: 'ANSD Sénégal', url: 'https://www.ansd.sn', type: 'institution', category: 'Affaires' },
      { name: 'Google Ateliers Numériques', url: 'https://learndigital.withgoogle.com/ateliersnumeriques', type: 'education', category: 'Marketing' },
      { name: 'Meta Business', url: 'https://www.facebook.com/business', type: 'business', category: 'Marketing' },
      { name: 'APIX Sénégal', url: 'https://www.investinsenegal.sn', type: 'institution', category: 'Croissance' },
    ],
  },
  {
    countryCode: 'ci',
    language: 'fr',
    locale: 'fr-CI',
    countryName: "Côte d'Ivoire",
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
      'IA',
      'Croissance',
      'Ventes',
      'E-commerce',
    ],
    topics: [
      'création entreprise Côte d\'Ivoire',
      'DGI Côte d\'Ivoire déclaration fiscale',
      'gestion PME Abidjan',
      'SYSCOHADA Côte d\'Ivoire',
      'Orange Money MTN MoMo commerce Abidjan',
      'logiciel gestion restaurant maquis Abidjan',
      'TVA Côte d\'Ivoire entreprises',
      'marketing digital PME Abidjan',
      'publicité Facebook Instagram Abidjan',
      'WhatsApp Business vente Côte d\'Ivoire',
      'vendre en ligne Abidjan',
      'e-commerce PME Côte d\'Ivoire',
      'intelligence artificielle entreprises CI',
      'développer son entreprise Abidjan',
      'expansion PME Côte d\'Ivoire',
      'digitalisation commerce Cocody',
      'caisse POS boutique Abidjan',
      'RCCM entreprise Côte d\'Ivoire',
    ],
    sources: [
      { name: 'DGI Côte d\'Ivoire', url: 'https://www.dgi.gouv.ci', type: 'government', category: 'Fiscalité' },
      { name: 'CEPICI', url: 'https://www.cepici.gouv.ci', type: 'institution', category: 'Entrepreneuriat' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution', category: 'Fiscalité' },
      { name: 'CCI Abidjan', url: 'https://www.cci.ci', type: 'business', category: 'Entrepreneuriat' },
      { name: 'Orange Côte d\'Ivoire', url: 'https://www.orange.ci', type: 'business', category: 'Technologie' },
      { name: 'Ministère du Commerce', url: 'https://www.commerce.gouv.ci', type: 'government', category: 'Commerce' },
      { name: 'ARTCI', url: 'https://www.artci.ci', type: 'institution', category: 'Technologie' },
      { name: 'Google Ateliers Numériques', url: 'https://learndigital.withgoogle.com/ateliersnumeriques', type: 'education', category: 'Marketing' },
      { name: 'Meta Business', url: 'https://www.facebook.com/business', type: 'business', category: 'Marketing' },
      { name: 'ANADER', url: 'https://www.anader.ci', type: 'institution', category: 'Croissance' },
    ],
  },
  {
    countryCode: 'ao',
    language: 'pt',
    locale: 'pt-AO',
    countryName: 'Angola',
    enabled: true,
    categories: ['Fiscalidade', 'Negócios', 'Empreendedorismo', 'Tecnologia', 'Marketing', 'Gestão', 'PME', 'IA', 'Crescimento', 'Vendas', 'E-commerce'],
    topics: [
      'criar empresa Angola',
      'gestão PME Luanda',
      'AGT impostos Angola',
      'IVA Angola empresas',
      'software gestão comercial Angola',
      'POS loja Angola',
      'contabilidade PME Angola',
      'marketing digital Angola',
      'publicidade Facebook Instagram Angola',
      'WhatsApp Business vendas Angola',
      'vender online Angola',
      'e-commerce PME Luanda',
      'inteligência artificial empresas Angola',
      'crescer negócio Angola',
      'expansão PME Luanda',
    ],
    sources: [
      { name: 'AGT Angola', url: 'https://www.agt.minfin.gov.ao', type: 'government', category: 'Fiscalidade' },
      { name: 'MINCOM', url: 'https://www.minc.gov.ao', type: 'government', category: 'Tecnologia' },
      { name: 'IAPI', url: 'https://www.iapi.gov.ao', type: 'institution', category: 'Empreendedorismo' },
      { name: 'CCIA', url: 'https://www.ccia.gov.ao', type: 'business', category: 'Negócios' },
      { name: 'Google Ateliers Numériques', url: 'https://learndigital.withgoogle.com/ateliersnumeriques', type: 'education', category: 'Marketing' },
      { name: 'Meta Business', url: 'https://www.facebook.com/business', type: 'business', category: 'Marketing' },
    ],
  },
  {
    countryCode: 'mz',
    language: 'pt',
    locale: 'pt-MZ',
    countryName: 'Moçambique',
    enabled: true,
    categories: ['Fiscalidade', 'Negócios', 'Empreendedorismo', 'Tecnologia', 'Marketing', 'Gestão', 'PME', 'IA', 'Crescimento', 'Vendas', 'E-commerce'],
    topics: [
      'criar empresa Moçambique',
      'gestão PME Maputo',
      'AT impostos Moçambique',
      'IVA Moçambique empresas',
      'software gestão restaurante Maputo',
      'controlo stock loja Moçambique',
      'M-Pesa negócios Moçambique',
      'ERP pequenas empresas Moçambique',
      'marketing digital Moçambique',
      'publicidade Facebook Instagram Maputo',
      'WhatsApp Business vendas Moçambique',
      'vender online Moçambique',
      'e-commerce PME Maputo',
      'inteligência artificial empresas Moçambique',
      'crescer negócio Moçambique',
      'expansão PME Maputo',
    ],
    sources: [
      { name: 'Autoridade Tributária', url: 'https://www.at.gov.mz', type: 'government', category: 'Fiscalidade' },
      { name: 'IPEME', url: 'https://www.ipeme.gov.mz', type: 'institution', category: 'Empreendedorismo' },
      { name: 'CENFACIL', url: 'https://www.cenfacil.gov.mz', type: 'institution', category: 'Gestão' },
      { name: 'ACIS', url: 'https://www.acis.org.mz', type: 'business', category: 'Negócios' },
      { name: 'Google Ateliers Numériques', url: 'https://learndigital.withgoogle.com/ateliersnumeriques', type: 'education', category: 'Marketing' },
      { name: 'Meta Business', url: 'https://www.facebook.com/business', type: 'business', category: 'Marketing' },
    ],
  },
];
