import type { CountryAiSettings } from '../types';

export const COUNTRY_AI_CONFIGS: CountryAiSettings[] = [
  {
    countryCode: 'gn',
    language: 'fr',
    locale: 'fr-GN',
    countryName: 'Guinée',
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
    ],
    topics: [
      'création entreprise Guinée',
      'gestion PME Conakry',
      'fiscalité DGI Guinée',
      'TVA 18% Guinée',
      'SYSCOHADA OHADA',
      'Orange Money commerce',
      'caisse POS Guinée',
      'marketing digital PME',
      'intelligence artificielle entreprises',
      'productivité commerçants',
    ],
    sources: [
      { name: 'DGI Guinée', url: 'https://www.dgi.gov.gn', type: 'government' },
      { name: 'Présidence de la République', url: 'https://presidence.gov.gn', type: 'government' },
      { name: 'BCRG — Banque Centrale', url: 'https://www.bcrg-guinee.org', type: 'institution' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution' },
      { name: 'Orange Guinée Business', url: 'https://www.orangeguinee.com', type: 'business' },
    ],
  },
  {
    countryCode: 'sn',
    language: 'fr',
    locale: 'fr-SN',
    countryName: 'Sénégal',
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
    ],
    topics: [
      'création entreprise Sénégal',
      'DGI Sénégal déclaration fiscale',
      'gestion PME Dakar',
      'SYSCOHADA Sénégal',
      'Wave Orange Money commerce Sénégal',
      'logiciel gestion restaurant Dakar',
      'TVA Sénégal entreprises',
      'marketing digital PME Sénégal',
      'caisse POS boutique Dakar',
      'NINEA entreprise Sénégal',
      'digitalisation commerce Sandaga',
    ],
    sources: [
      { name: 'Ministère des Finances', url: 'https://www.finances.gouv.sn', type: 'government' },
      { name: 'Ministère de l\'Économie', url: 'https://www.economie.gouv.sn', type: 'government' },
      { name: 'Secrétariat d\'État à la Simplification', url: 'https://www.sec.gouv.sn', type: 'institution' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution' },
      { name: 'CCIS', url: 'https://www.ccis.sn', type: 'business' },
      { name: 'ADEPME', url: 'https://www.adepme.sn', type: 'institution' },
      { name: 'Orange Sénégal Business', url: 'https://www.orange.sn', type: 'business' },
    ],
  },
  {
    countryCode: 'ci',
    language: 'fr',
    locale: 'fr-CI',
    countryName: "Côte d'Ivoire",
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
    ],
    topics: [
      'création entreprise Côte d\'Ivoire',
      'DGI Côte d\'Ivoire déclaration fiscale',
      'gestion PME Abidjan',
      'SYSCOHADA Côte d\'Ivoire',
      'Orange Money MTN MoMo commerce Abidjan',
      'logiciel gestion restaurant maquis Abidjan',
      'TVA Côte d\'Ivoire entreprises',
      'marketing digital PME Abidjan',
      'digitalisation commerce Cocody',
      'caisse POS boutique Abidjan',
      'RCCM entreprise Côte d\'Ivoire',
    ],
    sources: [
      { name: 'DGI Côte d\'Ivoire', url: 'https://www.dgi.gouv.ci', type: 'government' },
      { name: 'CEPICI', url: 'https://www.cepici.gouv.ci', type: 'institution' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution' },
      { name: 'CCI Abidjan', url: 'https://www.cci.ci', type: 'business' },
      { name: 'Orange Côte d\'Ivoire', url: 'https://www.orange.ci', type: 'business' },
      { name: 'Ministère du Commerce', url: 'https://www.commerce.gouv.ci', type: 'government' },
      { name: 'ARTCI', url: 'https://www.artci.ci', type: 'institution' },
    ],
  },
  {
    countryCode: 'ao',
    language: 'pt',
    locale: 'pt-AO',
    countryName: 'Angola',
    enabled: true,
    categories: ['Fiscalidade', 'Negócios', 'Empreendedorismo', 'Tecnologia', 'Marketing', 'Gestão', 'PME'],
    topics: [
      'criar empresa Angola',
      'gestão PME Luanda',
      'AGT impostos Angola',
      'IVA Angola empresas',
      'software gestão comercial Angola',
      'POS loja Angola',
      'contabilidade PME Angola',
      'marketing digital Angola',
    ],
    sources: [
      { name: 'AGT Angola', url: 'https://www.agt.minfin.gov.ao', type: 'government' },
      { name: 'MINCOM', url: 'https://www.minc.gov.ao', type: 'government' },
      { name: 'IAPI', url: 'https://www.iapi.gov.ao', type: 'institution' },
      { name: 'CCIA', url: 'https://www.ccia.gov.ao', type: 'business' },
    ],
  },
  {
    countryCode: 'mz',
    language: 'pt',
    locale: 'pt-MZ',
    countryName: 'Moçambique',
    enabled: true,
    categories: ['Fiscalidade', 'Negócios', 'Empreendedorismo', 'Tecnologia', 'Marketing', 'Gestão', 'PME'],
    topics: [
      'criar empresa Moçambique',
      'gestão PME Maputo',
      'AT impostos Moçambique',
      'IVA Moçambique empresas',
      'software gestão restaurante Maputo',
      'controlo stock loja Moçambique',
      'M-Pesa negócios Moçambique',
      'ERP pequenas empresas Moçambique',
    ],
    sources: [
      { name: 'Autoridade Tributária', url: 'https://www.at.gov.mz', type: 'government' },
      { name: 'IPEME', url: 'https://www.ipeme.gov.mz', type: 'institution' },
      { name: 'CENFACIL', url: 'https://www.cenfacil.gov.mz', type: 'institution' },
      { name: 'ACIS', url: 'https://www.acis.org.mz', type: 'business' },
    ],
  },
];
