import type { CountryAiSettings } from '../types';

export const COUNTRY_AI_CONFIGS: CountryAiSettings[] = [
  {
    countryCode: 'gn',
    language: 'fr',
    locale: 'fr-GN',
    countryName: 'Guinée',
    enabled: true,
    categories: [
      'Fiscalité',
      'Affaires',
      'Entrepreneuriat',
      'Technologie',
      'Marketing',
      'Gestion',
      'Commerce',
      'PME',
    ],
    topics: [
      'création entreprise Guinée',
      'gestion PME Conakry',
      'fiscalité DGI Guinée',
      'TVA 18% Guinée',
      'SYSCOHADA OHADA',
      'Orange Money commerce',
      'caisse POS Guinée',
      'marketing digital PME',
      'intelligence artificielle entreprises',
      'productivité commerçants',
    ],
    sources: [
      { name: 'DGI Guinée', url: 'https://www.dgi.gov.gn', type: 'government' },
      { name: 'Ministère du Commerce', url: 'https://www.commerce.gov.gn', type: 'government' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution' },
      { name: 'ANSS', url: 'https://anss.gov.gn', type: 'government' },
      { name: 'CCIG', url: 'https://ccig.org.gn', type: 'business' },
      { name: 'Orange Guinée Business', url: 'https://www.orangeguinee.com', type: 'business' },
    ],
  },
  {
    countryCode: 'sn',
    language: 'fr',
    locale: 'fr-SN',
    countryName: 'Sénégal',
    enabled: true,
    categories: ['Fiscalité', 'Entrepreneuriat', 'Technologie', 'Marketing', 'Gestion', 'Commerce', 'PME'],
    topics: [
      'création entreprise Sénégal',
      'DGI Sénégal déclaration fiscale',
      'gestion PME Dakar',
      'SYSCOHADA Sénégal',
      'Orange Money commerce Sénégal',
      'logiciel gestion restaurant Dakar',
      'TVA Sénégal entreprises',
      'marketing digital PME Sénégal',
    ],
    sources: [
      { name: 'DGI Sénégal', url: 'https://www.impots.gouv.sn', type: 'government' },
      { name: 'APIX', url: 'https://www.apix.sn', type: 'institution' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution' },
      { name: 'CCIS', url: 'https://www.ccis.sn', type: 'business' },
    ],
  },
  {
    countryCode: 'ci',
    language: 'fr',
    locale: 'fr-CI',
    countryName: "Côte d'Ivoire",
    enabled: true,
    categories: ['Fiscalité', 'Entrepreneuriat', 'Technologie', 'Marketing', 'Gestion', 'Commerce', 'PME'],
    topics: [
      'création entreprise Côte d\'Ivoire',
      'DGI Côte d\'Ivoire déclaration fiscale',
      'gestion PME Abidjan',
      'SYSCOHADA Côte d\'Ivoire',
      'Orange Money commerce Abidjan',
      'MTN MoMo caisse Côte d\'Ivoire',
      'logiciel gestion restaurant maquis Abidjan',
      'TVA Côte d\'Ivoire entreprises',
      'marketing digital PME Abidjan',
      'digitalisation commerce Cocody',
    ],
    sources: [
      { name: 'DGI Côte d\'Ivoire', url: 'https://www.dgi.gouv.ci', type: 'government' },
      { name: 'CEPICI', url: 'https://www.cepici.gouv.ci', type: 'institution' },
      { name: 'OHADA', url: 'https://www.ohada.org', type: 'institution' },
      { name: 'CCI Abidjan', url: 'https://www.cci.ci', type: 'business' },
      { name: 'Orange Côte d\'Ivoire', url: 'https://www.orange.ci', type: 'business' },
    ],
  },
  {
    countryCode: 'ao',
    language: 'pt',
    locale: 'pt-AO',
    countryName: 'Angola',
    enabled: true,
    categories: ['Fiscalidade', 'Negócios', 'Empreendedorismo', 'Tecnologia', 'Marketing', 'Gestão', 'PME'],
    topics: [
      'criar empresa Angola',
      'gestão PME Luanda',
      'AGT impostos Angola',
      'IVA Angola empresas',
      'software gestão comercial Angola',
      'POS loja Angola',
      'contabilidade PME Angola',
      'marketing digital Angola',
    ],
    sources: [
      { name: 'AGT Angola', url: 'https://www.agt.minfin.gov.ao', type: 'government' },
      { name: 'MINCOM', url: 'https://www.minc.gov.ao', type: 'government' },
      { name: 'IAPI', url: 'https://www.iapi.gov.ao', type: 'institution' },
      { name: 'CCIA', url: 'https://www.ccia.gov.ao', type: 'business' },
    ],
  },
  {
    countryCode: 'mz',
    language: 'pt',
    locale: 'pt-MZ',
    countryName: 'Moçambique',
    enabled: true,
    categories: ['Fiscalidade', 'Negócios', 'Empreendedorismo', 'Tecnologia', 'Marketing', 'Gestão', 'PME'],
    topics: [
      'criar empresa Moçambique',
      'gestão PME Maputo',
      'AT impostos Moçambique',
      'IVA Moçambique empresas',
      'software gestão restaurante Maputo',
      'controlo stock loja Moçambique',
      'M-Pesa negócios Moçambique',
      'ERP pequenas empresas Moçambique',
    ],
    sources: [
      { name: 'Autoridade Tributária', url: 'https://www.at.gov.mz', type: 'government' },
      { name: 'IPEME', url: 'https://www.ipeme.gov.mz', type: 'institution' },
      { name: 'CENFACIL', url: 'https://www.cenfacil.gov.mz', type: 'institution' },
      { name: 'ACIS', url: 'https://www.acis.org.mz', type: 'business' },
    ],
  },
];
